/oak:
  ros__parameters:
    driver:
      i_usb_speed: SUPER
    pipeline_gen:
      i_nn_type: none
      i_pipeline_type: RGB
      i_enable_imu: true
    rgb:
      i_fps: 30.0
      i_isp_num: 1
      i_isp_den: 4
      i_low_bandwidth: true
      i_low_bandwidth_quality: 50
      i_publish_topic: true
    imu:
      i_acc_freq: 200
      i_gyro_freq: 200
      i_max_batch_reports: 1
      i_batch_report_threshold: 1
    left:
      i_publish_topic: false
    right:
      i_publish_topic: false
    stereo:
      i_publish_left_rect: false
      i_publish_right_rect: false
      i_publish_synced_rect_pair: false
      i_publish_topic: false
